name: Frontend Develop Workflow

on:
  push:
    branches: 
      - develop
    
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy Frontend to EC2 Server
        uses: applyboy/ssh-action@v1
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SECRET_KEY }}
          script: |
            'sh deploy_frontend.sh'